tap "dart-lang/dart"
tap "henkrehorst/php"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/versions"
tap "sass/sass"
brew "openssl@1.1"
brew "readline"
brew "xz"
brew "python@3.8"
brew "awscli"
brew "libffi"
brew "python@3.9"
brew "cairo"
brew "cmake"
brew "composer"
brew "dnsmasq", link: false
brew "libevent"
brew "jpeg"
brew "ffmpeg"
brew "gdk-pixbuf"
brew "geoip"
brew "gifsicle"
brew "libheif"
brew "imagemagick"
brew "jsonpp"
brew "libpq"
brew "libxml2"
brew "lynx"
brew "mailhog", restart_service: true
brew "mysql-utilities"
brew "mysql@5.7", link: true
brew "nginx"
brew "node"
brew "node@10"
brew "osmfilter"
brew "osmosis"
brew "pandoc"
brew "pango"
brew "php", restart_service: true
brew "php@7.2"
brew "pv"
brew "pyenv"
brew "redis", restart_service: true
brew "ruby"
brew "wget"
brew "wp-cli"
brew "zlib"
brew "sass/sass/sass", link: false
cask "sequel-pro"
